# Generated by Django 4.0.3 on 2022-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcRouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busType', models.CharField(max_length=100)),
                ('busClass', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
