# Generated by Django 4.0.3 on 2022-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_abcroutedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcroutedetail',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='abcrouteselection',
            name='date',
            field=models.DateField(),
        ),
    ]
