# Generated by Django 4.0.3 on 2022-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_abcroutedetail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcroutedetail',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
