# Generated by Django 4.0.3 on 2022-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_abcroutedetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcTestRouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busType', models.CharField(max_length=100)),
                ('busClass', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='AbcRouteSelection',
            new_name='AbcTestRouteSelection',
        ),
        migrations.DeleteModel(
            name='AbcRouteDetail',
        ),
    ]
