# Generated by Django 4.0.3 on 2022-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_abctestroutedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcDetailRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busType', models.CharField(max_length=100)),
                ('busClass', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AbcSelectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='AbcTestRouteDetail',
        ),
        migrations.DeleteModel(
            name='AbcTestRouteSelection',
        ),
    ]
