# Generated by Django 4.0.3 on 2022-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_abcdetailroute_abcselectionroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcPersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
